version: '3'

services:

    nginx:
        build: ./.docker/nginx/
        ports:
            - 80:80
        volumes:
            - ./:/code
            - ./.docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log:/var/log/nginx
        links:
            - php:php

    php:
        build: ./.docker/php/
        ports:
            - 9000:9000
        volumes:
            - ./:/code
            - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
        links:
            - db:db
               
    db:
        build: ./.docker/mysql/
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: techband
        command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
        volumes:
            - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"